#!/usr/bin/env node
// Downloads fonts into <project>/assets/fonts and writes <project>/assets/fonts.css (the scene links it).
//
// Google Fonts:      node fonts.mjs <project> "Big Shoulders:600,700,800,900" "Barlow:400,500,600,700"
// From a live app:   node fonts.mjs <project> --from-url http://localhost:3000     (grabs the @font-face the app really serves)
//
// Local font files are also fine: copy them to assets/fonts and add @font-face rules to fonts.css by hand.
import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const argv = process.argv.slice(2);
const PROJECT = resolve(argv[0] ?? ".");
const DIR = join(PROJECT, "assets", "fonts");
await mkdir(DIR, { recursive: true });
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36"; // → woff2

async function localize(cssText, baseUrl, prefix) {
  const blocks = cssText.match(/@font-face\s*{[^}]*}/g) ?? [];
  const out = [], seen = new Map();
  for (const b of blocks) {
    const m = b.match(/url\(\s*["']?([^"')]+)["']?\s*\)/);
    if (!m || m[1].startsWith("data:")) { out.push(b); continue; }
    const abs = new URL(m[1], baseUrl).href;
    if (!seen.has(abs)) {
      const res = await fetch(abs, { headers: { "user-agent": UA } });
      if (!res.ok) { console.warn(`  skip ${abs} (${res.status})`); continue; }
      const ext = (abs.match(/\.(woff2|woff|ttf|otf)(\?|$)/)?.[1]) ?? "woff2";
      const file = `${prefix}-${seen.size}.${ext}`;
      await writeFile(join(DIR, file), Buffer.from(await res.arrayBuffer()));
      seen.set(abs, file);
    }
    // font-display: block → never render a fallback frame
    out.push(b.replace(/src:[^;]*;/, `src: url("fonts/${seen.get(abs)}") format("${seen.get(abs).split(".").pop() === "ttf" ? "truetype" : seen.get(abs).split(".").pop()}");`).replace(/font-display:\s*\w+;?/, "").replace("{", "{ font-display: block;"));
  }
  return { css: out.join("\n"), files: seen.size };
}

let css = "", families = [];
const fromUrl = argv.indexOf("--from-url") >= 0 ? argv[argv.indexOf("--from-url") + 1] : null;
if (fromUrl) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const sheets = [];
  page.on("response", async (r) => { if ((r.headers()["content-type"] ?? "").includes("text/css")) sheets.push({ url: r.url(), text: await r.text().catch(() => "") }); });
  await page.goto(fromUrl, { waitUntil: "networkidle" });
  const inline = await page.evaluate(() => [...document.querySelectorAll("style")].map((s) => s.textContent).join("\n"));
  sheets.push({ url: fromUrl, text: inline });
  await browser.close();
  let k = 0;
  for (const s of sheets) { const r = await localize(s.text, s.url, `site${k++}`); if (r.css.trim()) css += r.css + "\n"; }
  families = [...new Set([...css.matchAll(/font-family:\s*["']?([^;"']+)["']?;/g)].map((m) => m[1].trim()))];
} else {
  const specs = argv.slice(1).filter((a) => !a.startsWith("--"));
  if (!specs.length) { console.error('usage: node fonts.mjs <project> "Family:400,700" ... | --from-url <url>'); process.exit(1); }
  for (const spec of specs) {
    const [family, weights = "400,700"] = spec.split(":");
    const q = `family=${encodeURIComponent(family.trim()).replace(/%20/g, "+")}:wght@${weights.split(",").map((w) => w.trim()).sort((a, b) => a - b).join(";")}&display=block`;
    const res = await fetch(`https://fonts.googleapis.com/css2?${q}`, { headers: { "user-agent": UA } });
    if (!res.ok) { console.error(`✗ Google Fonts has no "${family}" with weights ${weights} (HTTP ${res.status}). Check the exact family name at fonts.google.com.`); process.exit(1); }
    const r = await localize(await res.text(), "https://fonts.googleapis.com/", family.trim().toLowerCase().replace(/\W+/g, "-"));
    css += `/* ${family.trim()} ${weights} — Google Fonts (OFL) */\n${r.css}\n`;
    families.push(family.trim());
  }
}
await writeFile(join(PROJECT, "assets", "fonts.css"), `/* generated by fonts.mjs */\n${css}`);
console.log(`✓ assets/fonts.css — families: ${families.join(", ") || "(none found)"}`);
const faces = [...new Set([...css.matchAll(/@font-face\s*{[^}]*}/g)].map((m) => {
  const fam = /font-family:\s*["']?([^;"']+)/.exec(m[0])?.[1];
  const w = /font-weight:\s*([\d ]+)/.exec(m[0])?.[1]?.trim() ?? "400";
  return `${w.split(" ").pop()} 100px '${fam}'`; // variable fonts ("100 900") → the heaviest weight as a hint
}))];
console.log(`  Available faces (use these weights in CSS and list them in Motion.init({ fonts })):
  ${JSON.stringify(faces)}`);
